version: '3.1'
services:
  wkd:
    build: mykwd
    restart: always     
    ports:
      - 5555:5555 
    networks:
      - traefik-network

networks:
  traefik-network:
    external:
      name: traefik_proxynet
